language: node_js
matrix:
  include:
    - node_js: "6.0"
sudo: required
dist: trusty
addons:
  apt:
    packages:
    - nginx
    - curl
before_script:
  - export PATH=$(pwd)
  - PATH
  #Install self signed cert
  - sudo cp ssl/server.crt /usr/local/share/ca-certificates/certificate.crt
  - sudo update-ca-certificates
script:
  #Setup nginx
  - sudo cp .travis_nginx.conf /etc/nginx/nginx.conf
  - sudo nginx -c /etc/nginx/nginx.conf -t
  #Restart nginx
  - sudo /etc/init.d/nginx restart
  #Test http
  - curl http://localhost/
  #Test https insecure
  - curl https://localhost/ -k
  #Test https
  - curl https://localhost/
notifications:
  email: false