language: node_js
matrix:
  include:
    - node_js: "6.0"
sudo: required
dist: trusty
addons:
  apt:
    packages:
    - nginx
    - curl
#before_install:

before_script:
  
script:
  - pwd
  - ls
  - sudo cp .travis_nginx.conf /etc/nginx/nginx.conf
  - sudo nginx -c /etc/nginx/nginx.conf -t
  - sudo /etc/init.d/nginx restart
  - sleep 5
  - curl http://localhost/
  - curl https://localhost/
#after_script:

notifications:
  email: false