language: node_js
matrix:
  include:
    - node_js: "6.0"
sudo: required
dist: trusty
addons:
  apt:
    packages:
    - nginx
    - curl
    - libnss3-tools
    - expect
#before_install:

before_script:
  #Setup SSL db
  - mkdir -p $HOME/.pki/nssdb
  - chmod a+x create_certutil_db.sh
  - ./create_certutil_db.sh
  #Add SSL cert to trusted
  - certutil -d sql:$HOME/.pki/nssdb -A -t P -n 'localhost-cert' -i ssl/server.crt
script:
  - pwd
  - ls
  - sudo cp .travis_nginx.conf /etc/nginx/nginx.conf
  - sudo nginx -c /etc/nginx/nginx.conf -t
  - sudo /etc/init.d/nginx restart
  - sleep 5
  - curl http://localhost/
  - curl https://localhost/ -k
  - curl https://localhost/
#after_script:

notifications:
  email: false