language: node_js
matrix:
  include:
    - node_js: "6.0"
sudo: required
dist: trusty
addons:
  apt:
    packages:
    - nginx
    - curl
#before_install:

before_script:
  
script:
  - export ENV_PWD_PATH=pwd
  - sudo cp .travis_nginx.conf /etc/nginx/nginx.conf
  - sudo nginx -c /etc/nginx/nginx.conf -t
  - sudo /etc/init.d/nginx reload
  - nginx -g 'daemon off; load_module /etc/nginx/modules/ngx_http_perl_module-debug.so;'
  - curl http://localhost/
#after_script:

notifications:
  email: false